---
- hosts: all
  remote_user: isucon
  become: yes
  become_method: sudo

  roles:
    - packages-apt
    # - epel
    # - packages-yum

    - go
    - gcp
    - tmux-conf
    - pprotein

    - sysctl
    - limits

    - apparmor
    # - selinux

    - alp
    - netdata

- hosts: isu1
  remote_user: isucon
  become: yes
  become_method: sudo

  roles:
    # - nginx
    # - redis

- hosts: isu2
  remote_user: isucon
  become: yes
  become_method: sudo

  roles:

- hosts: isu3
  remote_user: isucon
  become: yes
  become_method: sudo

  roles: