---
- hosts: all
  remote_user: isucon
  become: yes
  become_method: sudo

  roles:
    - packages-apt
    - sysctl
    - limits
    - apparmor
    # - selinux
    - netdata

- hosts: isu1
  remote_user: isucon
  become: yes
  become_method: sudo

  roles:
    # - redis

- hosts: isu2
  remote_user: isucon
  become: yes
  become_method: sudo

  roles:

- hosts: isu3
  remote_user: isucon
  become: yes
  become_method: sudo

  roles: