---
- name: Install required packages with apt
  apt:
    name:
      - curl
      - tmux
      - git
      - wget
      - vim
      - graphviz
      - htop
      - percona-toolkit
      - tree
    state: latest
    update_cache: yes
