---
- name: Register user variables
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
  register: user_registered
  become: false

- name: Install .tmux.conf
  ansible.builtin.copy:
    src: ".tmux.conf"
    dest: "{{ user_registered.home }}"
    mode: preserve
  become: false
