---
- name: Install required packages with yum
  yum:
    name:
      - curl
      - tmux
      - git
      - wget
      - vim
      - graphviz
      - htop
      - percona-toolkit
    state: latest
    update_cahce: yes
