---

- name: Install Netdata stable repository configuration
  ansible.builtin.yum:
    name: https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-1-1.noarch.rpm/download.rpm
    state: present
  when: distro == 'stable'

- name: Import a stable repository PGP key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/netdata/netdata/gpgkey

- name: Install Netdata nightly repository configuration
  ansible.builtin.yum:
    name: https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-edge-1-1.noarch.rpm/download.rpm
    state: present
  when: distro == 'edge'

- name: Import an edge repository PGP key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/netdata/netdata-edge/gpgkey
