---

- name: Install some essential packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - gpg
    - debian-archive-keyring
    - apt-transport-https

- name: Install Netdata repo key
  ansible.builtin.apt_key:
    url: https://packagecloud.io/netdata/netdata-repoconfig/gpgkey
    state: present

- name: Install netdata repo
  ansible.builtin.apt:
    deb: "{{ repo_uri }}"
