---

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/netdata/netdata/gpgkey

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packagecloud.io/netdata/netdata-edge/gpgkey

- name: Install Netdata stable repository configuration
  ansible.builtin.dnf:
    name: https://packagecloud.io/netdata/netdata-repoconfig/packages/ol/8/netdata-repo-1-1.noarch.rpm/download.rpm
    state: present
    disable_gpg_check: true
  when: distro == 'stable'

- name: Install Netdata nightly repository configuration
  ansible.builtin.dnf:
    name: https://packagecloud.io/netdata/netdata-repoconfig/packages/ol/8/netdata-repo-edge-1-1.noarch.rpm/download.rpm
    state: present
    disable_gpg_check: true
  when: distro == 'edge'
