---

# We have to install the dependencies from EPEL because we have to disable it when installing netdata agent.

- name: Dependencies first
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - Judy
    - brotli
    - libuv
    - netcat
    - nodejs
    - nodejs-libs
    - openssl11
    - yum-plugin-priorities

# We disabled EPEL for netdata agent installation to exclude the possibility of installing EPEL package
- name: Install netdata agent package
  ansible.builtin.package:
    name: "{{ netdata_agent_package }}"
    state: latest
    update_cache: true
    disable_gpg_check: true
    disablerepo: "epel"

- name: Writing configuration to /etc/netdata/netdata.conf
  ansible.builtin.template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart netdata agent

- name: Start service "{{ netdata_agent_service }}"
  ansible.builtin.systemd:
    name: "{{ netdata_agent_service }}"
    state: started
    enabled: true
