---

- name: Dependencies first
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - Judy
    - brotli
    - libuv
    - netcat
    - nodejs
    - openssl

- name: Install the netdata agent package
  ansible.builtin.package:
    name: "{{ netdata_agent_package }}"
    state: latest
    update_cache: true
    disable_gpg_check: true
    disablerepo: "epel"

- name: Writing configuration to /etc/netdata/netdata.conf
  ansible.builtin.template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart netdata agent

- name: Start service "{{ netdata_agent_service }}"
  ansible.builtin.systemd:
    name: "{{ netdata_agent_service }}"
    state: started
    enabled: true
