---

- name: Install the netdata agent package
  ansible.builtin.package:
    name: "{{ netdata_agent_package }}"
    update_cache: true
    state: latest

- name: Start service "{{ netdata_agent_service }}"
  ansible.builtin.systemd:
    name: "{{ netdata_agent_service }}"
    state: started
    enabled: true
